version: '3'

services:

  db:
    image: mysql:latest
    container_name: bankappdbmysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 3523
      MYSQL_USER: root
      MYSQL_DATABASE: bankapp_db
    ports:
    - 3306:3306


  bank_service:
    build:
      context: .
    container_name: bank_app
    environment:
      DB_DB_HOST: jdbc:mysql://localhost:3306/bankapp_db
      DB_DB_USER: ${DB_USER}
      DB_DB_PASSWORD: ${DB_PASSWORD}
      DB_DB_NAME: bankapp_db
      CARD_CHECKING_SECURITY_JWT_SECRET: ${JWT_SECRET}
      CARD_CHECKING_SECURITY_ADMINS_SONIABOND_PASSWORD: ${DEFAULT_ADMIN_PASSWORD}
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  db-data:
    driver: local