version: '3'

services:
  bank_service:
    build:
      context: .
    container_name: bank_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/bankapp_db
      SPRING_DATASOURCE_PASSWORD: 3523
      CARD_CHECKING_SECURITY_JWT_SECRET: GnBGcKJvQJ93KCVVxXxkYL7RNWqYACCaMT9pNXmx7R949KKnrFsad3GVD3VkK3Qw
      CARD_CHECKING_SECURITY_ADMINS_SONIABOND_PASSWORD: password
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    image: postgres:latest
    container_name: bankappdb
    restart: always
    environment:
      POSTGRES_PASSWORD: 3523
      POSTGRES_DB: bankapp_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-data:
    driver: local