version: '3'

services:
  bank_service:
    image: bank_app:0.0.1-SNAPSHOT
    container_name: bank_app
    environment:
      MESSAGE_DB_HOST: db
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    image: postgres:latest
    container_name: bankappdb
    restart: always
    environment:
      POSTGRES_PASSWORD: 3523
      POSTGRES_DB: bankapp_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-data:
    driver: local